Added Portuguese string translation - value-pt
android/sunflower pull request #655
Opened 2020-09-23 08:43 UTC by anselmoalexandre

Hi @tiembo 
I hope you okay.

I was watching your video explaining how to use **Jetpack library Components** using **Sunflower Android app**, and I decided to help adding **_Portuguese language_** to this app which I found it helpful to control our plants needs.

Please, review and possibly merge this pull request into the master.
Thank you.

2020-10-23 00:49 UTC, Vgbhieel approved these changes
As a portuguese native speaker, I'd like to submit my feedback by saying that it's all fine.

2020-11-20 00:15 UTC, rosariopfernandes requested changes
I'm also a native Portuguese speaker.

Good work on these translations!
I just have a few comments and suggestions.

2020-11-20 00:15 UTC, rosariopfernandes commented on app/src/main/res/values-pt/strings.xml
> +    <string name="available" >Plantas disponíveis</string>
nit: unnecessary whitespace
```suggestion
    <string name="available">Plantas disponíveis</string>
```

2020-11-20 00:15 UTC, rosariopfernandes commented on app/src/main/res/values-pt/strings.xml
> +    <string name="add_plant" >Adicionar planta</string>
```suggestion
    <string name="add_plant">Adicionar planta</string>
```

2020-11-20 00:15 UTC, rosariopfernandes commented on app/src/main/res/values-pt/strings.xml
> +    <string name="garden_empty">Seu jardim esta vazio</string>
The correct spelling is with the accentuation
```suggestion
    <string name="garden_empty">Seu jardim está vazio</string>
```

2020-11-20 00:15 UTC, rosariopfernandes commented on app/src/main/res/values-pt/strings.xml
> +    <string name="gallery_title">Fotos tirados em Unsplash</string>
I think "Imagens" sounds better in this case.
```suggestion
    <string name="gallery_title">Imagens tiradas do Unsplash</string>
```

2020-11-20 00:15 UTC, rosariopfernandes commented on app/src/main/res/values-pt/strings.xml
> +        <item quantity="other">em cada %d dias</item>
I think "regar a cada 5 dias" sounds better than "regar em cada 5 dias"
```suggestion
        <item quantity="other">a cada %d dias</item>
```

2020-11-20 00:15 UTC, rosariopfernandes commented on app/src/main/res/values-pt/strings.xml
> +    <string name="gallery_content_description">Navegue para a tela de galeria</string>
"galeria" is a feminine noun
```suggestion
    <string name="gallery_content_description">Navegue para a tela da galeria</string>
```

2020-11-20 19:56 UTC, anselmoalexandre commented on app/src/main/res/values-pt/strings.xml
> +    <string name="add_plant" >Adicionar planta</string>
Thanks Rosario.

2021-06-15 18:02 UTC, calren approved these changes

2021-06-15 18:02 UTC, calren commented
this is fantastic, thanks @anselmoalexandre , @rosariopfernandes and @Vgbhieel !

2023-12-14 23:56 UTC, merged